name: Build Flow

on: [ push ]

jobs:
  build-backend:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk
#      - name: Build with lein
#        run: lein uberjar
#      - name: Run tests
#        run: lein test
