name: Build Flow

on: [ push ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup jdk'
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          java-package: jdk
      - name: 'Setup clojure tools'
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          lein: latest
      - name: Build with lein
        working-directory: './backend'
        run: lein uberjar
      - name: Run tests
        working-directory: './backend'
        run: lein test
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
      - name: 'Setup npm'
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: 'Install shadow-cljs'
        working-directory: './frontend'
        run: npm install -g shadow-cljs
      - name: 'Build frontend'
        working-directory: './frontend'
        run: npm run release
